### ISSUE TITLE
[TODO] change `imageUrl` to `image` 

### ISSUE THREAD

**Issue by yibeichan** [ReproNim/reproschema-protocol-cookiecutter#2]
in the current version, i changed `image` to `imageUrl` to pass the validation https://github.com/ReproNim/reproschema-protocol-cookiecutter/blob/30645d58a4d1aee15b6b4127a02451a6ba33ac7c/%7B%7Bcookiecutter.protocol_name%7D%7D/activities/voiceActivity/items/audio_image_record_item#L9
once this PR (https://github.com/ReproNim/reproschema/pull/453) is merged, we need to change it back to `image`

**Comment by satra** [comment]
i think i remember why we created imageUrl - to allow for validating. in generic, the only difference in imageUrl is the addition of type. so we should check how schema.org validates objects with multiple types.

**Comment by yibeichan** [comment]
@djarecka how's our current validation dealing with `imageUrl`? should we keep it or change it to `image`?

**Comment by djarecka** [comment]
change to `image`

**Comment by yibeichan** [comment]
okay, great!
